//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Recursos.HtmlResource", typeof(HtmlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;title&gt;Reporte&lt;/title&gt;&lt;style&gt;body{padding: 0px;margin: 0px;background-color: white;}body header{margin: 30px;padding: 20px;border: 1px solid lightgray;border-radius: 15px 15px;}body section{margin: 30px;padding: 20px;border: 1px solid lightgray;border-radius: 15px 15px;}body section #header{text-align: center;font-weight: bold;font-family: Arial, Helvetica, sans-serif;}table{width: 100%;border: 1px solid lightgray;border-radius: 5px 5px;padding: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td&gt;ROW1&lt;/td&gt;&lt;td&gt;ROW2&lt;/td&gt;&lt;td&gt;ROW3&lt;/td&gt;&lt;td&gt;ROW4&lt;/td&gt;&lt;td&gt;ROW5&lt;/td&gt;&lt;td&gt;ROW6&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;div id=&quot;header&quot;&gt;&lt;h2&gt;TABLENAME&lt;/h2&gt;&lt;/div&gt;&lt;div id=&quot;section&quot;&gt;&lt;table&gt;&lt;thead&gt;&lt;tr&gt;&lt;th&gt;Campo&lt;/th&gt;&lt;th&gt;Tipo de datos&lt;/th&gt;&lt;th&gt;Longitud&lt;/th&gt;&lt;th&gt;Null&lt;/th&gt;&lt;th&gt;Default&lt;/th&gt;&lt;th&gt;Restricción&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;ROWS&lt;/tbody&gt;&lt;/table&gt;&lt;br/&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
